-- SEQUENCE: public.gridid

-- DROP SEQUENCE IF EXISTS public.gridid;

CREATE SEQUENCE IF NOT EXISTS public.gridid
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

ALTER SEQUENCE public.gridid
    OWNER TO root;